### ISSUE TITLE
Version 1.2.2.1  -   Search Function issues

### ISSUE THREAD

**Issue by Irockus** [GroovemanAndCo/MyOhmStudio#1]
Issues

1.  Does not filter results, search does not filter list
2.  Search function causes app crash if criteria searched for is not in lowercase

searched for Jamie57lp and got this - retried other combos to determine when uppercase used,  it crashes

![image](https://user-images.githubusercontent.com/32970293/94165799-3946c700-fe50-11ea-8126-e889302251bf.png)

ver 1.0.1.00 - search works filters list, no crashes, uppercase letters used in search criteria are converted to lower case in search box after clicking contains button to execute search filter

**Comment by fab672000** [comment]
Fixed in 1.2.3
