### ISSUE TITLE
Display About box on launch of app with user checkbox at bottom to not display in the future (default unchecked), Modify about contents

### ISSUE THREAD

**Issue by Irockus** [GroovemanAndCo/MyOhmStudio#10]
Display About box content on launch of app with user checkbox at bottom to not display in the future (default unchecked)

**Modify About Box Content:**
This application allows you retrieve / listen / share all your ohmstudio session mixdowns, to browse through them and to provide you with a consolidated catalog.   

"MyOhmSessions" was developed by Fabien (a.k.a. Grooveman). 
Contributors:   _irockus, jamie57lp._

**Instructions:**

**Step 1:**     Go to [www.ohmstudio.com](url) web page and log in. 

**Step 2:**     Click on this link - [www.ohmstudio.com/v3/feed/my_projects?page=0](url)

_Your browser will return detailed information to the screen regarding your projects in a format which 
this program uses.  It is called a JSON file format._

**Step 3:**    Select and Copy the full text content  (Ctrl-A  followd by Ctrl-C in the browser)

**Step 4:**    Paste this information into a text editor (eg: Notepad) and save it to a file such as 
                    Myprojects.json to your Music folder.  (filename must end in .json)

**_Note:_** If you have more than 1000 projects, you will need to repeat this operation to gather the rest.  

If this is the case, you should repeat steps 2-4 above  

- in step 2 changing the last part of the URL - page=0, to page=1. (this will gather the information for the next 1000 projects)  
- in step 4, save it to a file such as Myprojects2.json  

More than 2000 projects,  repeat step 2-4 above changing URL suffix and file name accordingly

**Step 5:**  Click on the Open Button to select the file, it will automatically load your projects enabling 
                   you to download your mixdowns (.m4a files)

   _Note:_       The application will search your computer for JSON files, so you can also just close and relaunch the app
                   and it will automatically load and merge all the sessions for you.

This application represents a lot of after hours work, so if you'd like to support my future developments, you can click on the Donate button and buy me a coffee, thanks!

**Comment by fab672000** [comment]
Implemented in 1.3.1
